package com.example.cdc.multi;

import com.example.cdc.HeartbeatFilter;
import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.stream.Collectors;
import org.apache.flink.api.common.eventtime.WatermarkStrategy;
import org.apache.flink.cdc.connectors.base.options.StartupOptions;
import org.apache.flink.cdc.connectors.postgres.source.PostgresSourceBuilder;
import org.apache.flink.cdc.debezium.JsonDebeziumDeserializationSchema;
import org.apache.flink.configuration.Configuration;
import org.apache.flink.configuration.RestartStrategyOptions;
import org.apache.flink.connector.clickhouse.convertor.ClickHouseConvertor;
import org.apache.flink.connector.clickhouse.sink.ClickHouseAsyncSink;
import org.apache.flink.connector.clickhouse.sink.ClickHouseClientConfig;
import org.apache.flink.core.execution.CheckpointingMode;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.datastream.SingleOutputStreamOperator;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.api.functions.ProcessFunction;
import org.apache.flink.util.Collector;
import org.apache.flink.util.OutputTag;

/**
 * Stretch exercise: ONE Flink job, ONE Postgres replication slot, reading MULTIPLE tables
 * of DIFFERENT shapes -- proving the "group tables into a shared slot" scaling pattern
 * without hand-writing a POJO/parser/mapper per table (see com.example.cdc.CdcJob's
 * ResourceChange/DebeziumJsonParser/ResourceChangeMapper for the one-table, hand-typed
 * reference this generalizes). The tables and their ClickHouse column mappings come from
 * table-mappings.json (generated by scripts/generate_clickhouse_ddl.py), not from code.
 *
 * Does not touch flink_slot / flink_pub / cdc.resource_inventory used by CdcJob -- this job
 * uses its own slot (flink_multi_slot) and publication (flink_pub_multi), so the two can run
 * side by side without interfering.
 */
public class MultiTableCdcJob {

    public static void main(String[] args) throws Exception {
        String host = arg(args, "--host", "postgres");
        int port = Integer.parseInt(arg(args, "--port", "5432"));
        String mappingResource = arg(args, "--mappings", "table-mappings.json");

        List<TableMapping> mappings = TableMapping.loadAll(mappingResource);
        String tableList = mappings.stream()
                .map(m -> "public." + m.pgTable)
                .collect(Collectors.joining(","));

        Configuration conf = new Configuration();
        conf.set(RestartStrategyOptions.RESTART_STRATEGY, "fixed-delay");
        conf.set(RestartStrategyOptions.RESTART_STRATEGY_FIXED_DELAY_ATTEMPTS, 3);
        conf.set(RestartStrategyOptions.RESTART_STRATEGY_FIXED_DELAY_DELAY, Duration.ofSeconds(5));
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment(conf);
        env.enableCheckpointing(10_000, CheckpointingMode.EXACTLY_ONCE);
        env.getCheckpointConfig().setMinPauseBetweenCheckpoints(3_000);

        Properties debezium = new Properties();
        debezium.setProperty("publication.name", "flink_pub_multi");
        debezium.setProperty("publication.autocreate.mode", "disabled");
        debezium.setProperty("heartbeat.interval.ms", "5000");
        debezium.setProperty("heartbeat.action.query", "UPDATE cdc_heartbeat SET ts = now() WHERE id = 1");

        var source = PostgresSourceBuilder.PostgresIncrementalSource.<String>builder()
                .hostname(host).port(port).database("inventory").schemaList("public")
                .tableList(tableList)
                .username("cdc_user").password("cdc_pass")
                .slotName("flink_multi_slot")
                .decodingPluginName("pgoutput")
                .startupOptions(StartupOptions.initial())
                // includeSchema=false: GenericDebeziumJsonParser infers value types from JSON
                // alone, so schema metadata in every message would be pure overhead here.
                .deserializer(new JsonDebeziumDeserializationSchema(false, Map.of("decimal.format", "NUMERIC")))
                .debeziumProperties(debezium)
                .build();

        DataStream<GenericChange> changes = env
                .fromSource(source, WatermarkStrategy.noWatermarks(), "postgres-cdc-multi")
                .setParallelism(1)   // one replication slot: streaming is single-reader, same as CdcJob
                .filter(new HeartbeatFilter())
                .map(new GenericDebeziumJsonParser()).returns(GenericChange.class);

        // Route the one generic stream into one side output per table, by table name --
        // this is the fan-out that lets many tables share one source/one slot but still get
        // independently-typed, independently-batched ClickHouse sinks downstream.
        Map<String, OutputTag<GenericChange>> tags = new HashMap<>();
        for (TableMapping m : mappings) {
            tags.put(m.pgTable, new OutputTag<>(m.pgTable, org.apache.flink.api.common.typeinfo.TypeInformation.of(GenericChange.class)));
        }
        SingleOutputStreamOperator<GenericChange> tagged = changes.process(new ProcessFunction<GenericChange, GenericChange>() {
            @Override
            public void processElement(GenericChange c, Context ctx, Collector<GenericChange> out) {
                OutputTag<GenericChange> tag = tags.get(c.table);
                if (tag != null) {
                    ctx.output(tag, c);
                }
                // no default-output collect(): every routed record goes to exactly one side output
            }
        });

        for (TableMapping m : mappings) {
            ClickHouseClientConfig chConfig = new ClickHouseClientConfig(
                    "http://clickhouse:8123", "flink_sink", "flink_pass", "cdc", m.chTable);
            ClickHouseAsyncSink<GenericChange> sink = ClickHouseAsyncSink.<GenericChange>builder()
                    .setElementConverter(new ClickHouseConvertor<>(GenericChange.class, new GenericClickHouseMapper(m)))
                    .setClickHouseClientConfig(chConfig)
                    .setMaxBatchSize(500)
                    .setMaxTimeInBufferMS(2000)
                    .setMaxBatchSizeInBytes(1024 * 1024)
                    .setMaxInFlightRequests(2)
                    .setMaxBufferedRequests(5000)
                    .setMaxRecordSizeInBytes(4096)
                    .build();
            tagged.getSideOutput(tags.get(m.pgTable)).sinkTo(sink).name("sink-" + m.chTable);
        }

        env.execute("postgres-cdc-multi (" + mappings.size() + " tables, 1 slot)");
    }

    private static String arg(String[] args, String name, String dflt) {
        for (int i = 0; i < args.length - 1; i++) {
            if (name.equals(args[i])) return args[i + 1];
        }
        return dflt;
    }
}
